export const initialState = {
    loading: false,
    datalist: [],
    dataObj: {},
    usersData:[],
    perfumesData:[],
    selectedPerfume: null,
    brandData:[],
    history: [],
    chatbotMessages: [],
    favoritesData: [],
    reviewData: [],
    followBrandData: [],
    errorMessage: null,
    token: null,
};